# This is a basic workflow to help you get started with Actions

name: Scrap

# Controls when the action will run. 
on:
  schedule:
    - cron: "15,35 11-17 * * 1-5"
    - cron: "55 11-17 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scrap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Show current date
        run: date
        env:
          TZ: Europe/Prague

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
        name: "Checkout repository"

      - uses: actions/setup-python@main
        name: "Setup Python"
        with:
          python-version: "3.11"

      - name: "Install dependencies"
        run: "pip install -U pip requests lxml pdfminer.six"

      - name: "Scrapy scrap"
        run: "python happykaktus.py"
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHATID: "@kvetinac"

      - name: "Commit last state"
        run: |
          git config user.name "GitHub Action"
          git config user.email "robot@github.invalid"
          git add lastlink.txt || true
          git commit -m "Update last item (autocommit)" || true
          git push
